### ISSUE TITLE
Concurrent calls to client

### ISSUE THREAD

**Issue by maddie** [simonvetter/modbus#2]
Is it safe to call `client.Read*` methods concurrently?

**Comment by simonvetter** [comment]
yes, the client API is thread-safe: all exported methods acquire a mutex at some point.

See https://github.com/simonvetter/modbus/blob/master/client.go#L796 and https://github.com/simonvetter/modbus/blob/master/client.go#L706 for reads. Writes and other methods should all do something similar.

Let me know if you run into concurrency issues as that would definitely be a bug.

**Comment by maddie** [comment]
Good to know, thanks a lot!
