### ISSUE TITLE
Reading strings

### ISSUE THREAD

**Issue by guydillen** [simonvetter/modbus#8]
Hello,

I have a use case where I have to read consecutive strings: 15 bytes, 10 bytes and 10 bytes.
(How) can I achieve this with your library?

Thanks.
Guy

**Comment by simonvetter** [comment]
Sorry for the late reply, i've been fairly busy this week.

I had byte access methods baking in a branch somewhere, waiting to be cleaned up, tested and merged.
The latest release (v1.5.0) adds ReadBytes(), WriteBytes(), ReadRawBytes() and WriteRawBytes(). Does that help with your use case?

**Comment by simonvetter** [comment]
Going to close this for now since it's been left idle for a long time. Feel free to reopen if needed.
